### ISSUE TITLE
用pycharm打开，运行game.py后只有文字，不能加载出动画？？？

### ISSUE THREAD

**Issue by rootab** [xgnit/evolutionary-neural-network-autonomous-car#1]
![image](https://user-images.githubusercontent.com/44662170/76375190-253deb00-6380-11ea-8bda-5fd80d0cfe1c.png)

**Comment by xgnit** [comment]
啊，不好意思，因为他实际上是每一代生成一个gif，然后储存在res文件夹下，最后的结果就是一堆gif。所以这个gif没有自动播放，需要自己去看每一代gif是如何的。我忘记在结果输出一个提示了，谢谢。

其实我内嵌了一个gif播放器，就是之前调参的时候每一代需要的时间太久了。所以感觉每代结束播放没什么意义，就放弃了。现在进化的速度还可以

**Comment by rootab** [comment]
谢谢你。我晚上再看看。



---原始邮件---
发件人: "xgnit"<notifications@github.com&gt;
发送时间: 2020年3月11日(周三) 下午3:08
收件人: "xgnit/evolutionary-neural-network-autonomous-car"<evolutionary-neural-network-autonomous-car@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"rootab"<1007442283@qq.com&gt;;
主题: Re: [xgnit/evolutionary-neural-network-autonomous-car] 用pycharm打开，运行game.py后只有文字，不能加载出动画？？？ (#1)



啊，不好意思，因为他实际上是每一代生成一个gif，然后储存在res文件夹下，最后的结果就是一堆gif。所以这个gif没有自动播放，需要自己去看每一代gif是如何的。我忘记在结果输出一个提示了，谢谢。
 
其实我内嵌了一个gif播放器，就是之前调参的时候每一代需要的时间太久了。所以感觉每代结束播放没什么意义，就放弃了。现在进化的速度还可以
